import './globals.css'
import Navbar from '@/components/mollecules/Navbar';
import SocmedSide from '@/components/mollecules/SocmedSide';
import EmailSide from '@/components/mollecules/EmailSide';
import Footer from '@/components/mollecules/Footer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={ "scrollbar font-inter antialiased text-white bg-backgroundcolor scrollbar-rounded-xl  scrollbar scrollbar-thumb-slate scrollbar-track-transparent scrollbar-thumb-rounded-lg  scrollbar-w-[.4rem]"}>
      <Navbar/>
      <SocmedSide/>
      <EmailSide/>
      <main className='min-h-screen'>
        {children}
      </main>
      <Footer/>
      </body>
    </html>
  )
}
