import Head from 'next/head';
import './globals.css'
import {Inter} from "next/font/google";
import Navbar from '@/components/mollecules/Navbar';
import SocmedSide from '@/components/mollecules/SocmedSide';
import EmailSide from '@/components/mollecules/EmailSide';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({subsets : ['latin']})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <title>A|B</title>
      </Head>
      <body className={ inter.className + " antialiased  bg-backgroundcolor scrollbar-rounded-xl  scrollbar scrollbar-thumb-slate scrollbar-track-transparent scrollbar-thumb-rounded-lg  scrollbar-w-[.4rem]"}>
      <Navbar/>
      <SocmedSide/>
      <EmailSide/>
      <main>
        {children}
      </main>
      </body>
    </html>
  )
}
